# Kubernetes namespace to deploy OrientDB cluster
namespace: orientdb

statefulSetName: orientdb
serviceName: orientdb
labelValue: orientdb
# number of servers in the cluster
servers: 2

httpPort: 2480
httpNodePort: 30080
binaryPort: 2424
binaryNodePort: 30024

createRootUser: true
rootPassword: root

orientdbConfigMapName: orientdb-configmap

log:

image:
  repository: orientdb
  tag: 3.1.1
  pullPolicy: IfNotPresent

customSqlFunctions:
  enabled: true

automaticBackup:
  enabled: false

hazelcast:
  network:
    port: 2434
  group:
    name: orientdb
    password: orientdb
  properties:
    phoneHomeEnabled: false
    mancenterEnabled: false
    memcacheEnabled: false
    restEnabled: false
    waitSecondsBeforeJoin: 5
    operationThreadCount: 1
    ioThreadCount: 1
    operationGenericThreadCount: 1
    clientEventThreadCount: 1
    eventThreadCount: 1
    heartbeatIntervalSeconds: 5
    maxNoHeartbeatSeconds: 30
    mergeNextRunDelaySeconds: 15
  discovery:
    podLabel:
      name: orientdb-cluster-member
      value: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use or create.
  name: hazelcast-k8s

volumes:
  databases:
    storageClass: ""
    size: 2Gi
  config:
    storageClass: ""
    size: 100Mi

service:
  nodePort:
    create: true

