namespace: orientdb

master:
  name: orientdb
  serviceName: orientdb
  labelValue: orientdb
  replicas: 3

replica:
  name: orientdb-replica
  serviceName: orientdb-replica
  labelValue: orientdb-replica
  replicas: 0

httpPort: 2480
binaryPort: 2424
hazelcastPort: 2434

createRootUser: true
rootPassword: root

image:
  repository: orientdb
  tag: 3.1.1
  pullPolicy: IfNotPresent

hazelcastDiscovery:
  podLabel:
    name: orientdb-cluster-member
    value: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use or create.
  name: hazelcast-k8s

orientdbConfigMapName: orientdb-configmap

log:

service:
  type: ClusterIP
  port: 80

