apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.master.serviceName }}
  # labels could be a template function call
  labels:
    app: {{ .Values.master.labelValue }}
spec:
  ports:
  - port: {{ .Values.httpPort }}
    name: http
  - port: {{ .Values.binaryPort }}
    name: binary
  - port: {{ .Values.hazelcastPort }}
    name: hazelcast
  clusterIP: None
  selector:
    app: {{ .Values.master.labelValue }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.master.name }}
  labels:
    app: {{ .Values.master.labelValue }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.master.labelValue }}
  replicas: {{ .Values.master.replicas }}
  serviceName: {{ .Values.master.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.master.labelValue }}
        orientdb-cluster-member: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 30
      containers:
      - name: orientdb
        command: ["dserver.sh"]
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.httpPort }}
          protocol: TCP
        - containerPort: {{ .Values.binaryPort }}
          protocol: TCP
        - containerPort: {{ .Values.hazelcastPort }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: {{ .Values.binaryPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.binaryPort }}
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
        volumeMounts:
        - name: databases
          mountPath: /orientdb/databases
        - name: config
          mountPath: /orientdb/config
      # OrientDB needs the config files (at least server config) to be modifiable. Mounting directly from the configMap
      # would result in a read-only config folder which can crash the server.
      initContainers:
      - name: copy-configs
        image: busybox:1.31
        command: ['sh', '-c']
        args:
        - cp -v /orientdb-config/* /orientdb/config/
        volumeMounts:
        - name: config
          mountPath: /orientdb/config
        - name: orientdb-config-cm-vol
          mountPath: /orientdb-config
      volumes:
      - name: orientdb-config-cm-vol
        configMap:
          name: {{ .Values.orientdbConfigMapName }}
  volumeClaimTemplates:
  - metadata:
      name: databases
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.volumes.databases.storageClass }}
      resources:
        requests:
          storage: {{ .Values.volumes.databases.size }}
  - metadata:
      name: config
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.volumes.config.storageClass }}
      resources:
        requests:
          storage: {{ .Values.volumes.config.size }}