{{- if .Values.service.nodePort.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labelValue }}
spec:
  type: NodePort
  ports:
  - name: binary
    port: {{ .Values.binaryPort }}
    nodePort: {{ .Values.binaryNodePort }}
  - name: http
    port: {{ .Values.httpPort }}
    nodePort: {{ .Values.httpNodePort }}
  selector:
    app: {{ .Values.labelValue }}
{{- end -}}